apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: web
  labels:
    app: employees
spec:
  imagePullSecrets:
  - name: ecr-secret
  containers:
  - name: app
    image: 752935596486.dkr.ecr.us-east-1.amazonaws.com/clo835-app:latest
    ports:
    - containerPort: 8080
    env:
    - name: APP_COLOR
      value: "blue"
    - name: DBHOST
      value: "mysql-service.mysql.svc.cluster.local"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    - name: DATABASE
      value: "employees"