apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql
  labels:
    app: mysql
spec:
  imagePullSecrets:
  - name: ecr-secret
  containers:
  - name: mysql
    image: 752935596486.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"